server:
  port: 80
  
spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: cartServiceApp
          uri: lb://CART-SERVICE
          predicates:
          - path=/cart/**
        
        - id: orderServiceApp
          uri: lb://ORDER-SERVICE
          predicates:
          - path=/order/**
          
  application:
    name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka